### ISSUE TITLE
Add time with mentioned date

### ISSUE THREAD

**Issue by faisalamin001** [faisalamin001/Notes-app#4]
<img width="355" alt="Screenshot 2022-10-04 at 9 15 00 PM" src="https://user-images.githubusercontent.com/58821374/193871604-c6845355-f8e3-47b3-866a-abfe31460d2b.png">

**Comment by ujwalkumar1995** [comment]
Hey @faisalamin001 
I can work on this issue.

**Comment by faisalamin001** [comment]
I assigned this task to you
